import './styles/global.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Nav from './components/nav-comp';
import Footer from './components/footer-comp';

// Initialize the Inter font
const inter = Inter({ subsets: ['latin'] });

// Type-safe metadata
export const metadata: Metadata = {
  title: 'Welcome to my portfolio!',
  description: 'Generated by create-nx-workspace',
  // You can add more metadata properties:
  keywords: ['portfolio', 'web development', 'Rebecca Lang'],
  authors: [{ name: 'Rebecca Lang' }],
  // Add OpenGraph metadata for better social sharing
  openGraph: {
    title: 'Rebecca Lang Portfolio',
    description: 'Your professional portfolio',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="flex flex-col min-h-screen m-0 p-0 overflow-visible">
        <Nav />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
