services:
  - type: web
    name: r-lang-portfolio
    env: node
    plan: free
    nodeVersion: 18.17.0
    buildCommand: npm ci && npx nx build portfolio
    startCommand: npm run start-prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NX_VERBOSE_LOGGING
        value: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
