services:
  - type: web
    name: r-lang-portfolio
    env: node
    plan: free
    nodeVersion: 20.19.1
    buildCommand: npm ci --prefer-offline && npx nx build portfolio
    startCommand: cd dist/apps/portfolio && next start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NX_VERBOSE_LOGGING
        value: false
    healthCheckPath: /
    autoDeploy: true
    buildCache:
      paths:
        - node_modules/
        - apps/portfolio/.next/cache/
