services:
  - type: web
    name: r-lang-portfolio
    env: node
    plan: free
    nodeVersion: 20.19.1
    buildCommand: npm ci && rm -rf dist apps/portfolio/.next && cp apps/portfolio/next.config.prod.js apps/portfolio/next.config.js && cd apps/portfolio && npx next build
    startCommand: cd apps/portfolio && next start -p $PORT -H 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: NX_VERBOSE_LOGGING
        value: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    healthCheckPath: /
    autoDeploy: true
    buildCache:
      paths:
        - node_modules/
        - apps/portfolio/.next/cache/
