services:
  - type: web
    name: r-lang-portfolio
    env: node
    plan: free
    nodeVersion: 18.17.0
    buildCommand: npm ci --only=production && npx nx build portfolio
    startCommand: npx nx serve portfolio --prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NX_VERBOSE_LOGGING
        value: false
    healthCheckPath: /
    autoDeploy: true
