name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'npm'

      - run: npm ci
      - run: npx cypress install
      
      # Add node_modules/.bin to PATH for CI
      - name: Add node_modules/.bin to PATH
        run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH
      
      # Set SHAs for Nx affected commands
      - uses: nrwl/nx-set-shas@v4
      
      # Debug information
      - name: Debug environment
        run: |
          echo "NX_BASE: $NX_BASE"
          echo "NX_HEAD: $NX_HEAD"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Nx version: $(npx nx --version)"
          echo "Git status:"
          git status --porcelain
          echo "Git log (last 3 commits):"
          git log --oneline -3

      # Run lint and build first, then e2e tests
      - name: Run lint and build
        run: |
          # Use production config for CI builds to avoid Nx plugin issues
          cp apps/portfolio/next.config.prod.js apps/portfolio/next.config.js
          # Run lint through Nx (works fine)
          npx nx affected -t lint --verbose || npx nx run-many -t lint --projects=portfolio --verbose
          # Run build directly with Next.js to avoid Nx plugin conflicts
          cd apps/portfolio && npx next build
        env:
          NODE_ENV: production
          CI: true
          # Ensure consistent build environment
          NEXT_TELEMETRY_DISABLED: 1
          # Increase memory limit for CI
          NODE_OPTIONS: "--max-old-space-size=4096"
          # Enable Nx Cloud retry for flaky tasks
          NX_CLOUD_RETRY_FAILED_TASKS: true
          # Add API key for CI builds
          RESEND_API_KEY: "re_test_dummy_key_for_ci"
      
      - name: Restore original config
        run: git checkout apps/portfolio/next.config.js
      
      - name: Run e2e tests
        run: npx nx affected -t e2e --spec="apps/r-lang-portfolio-e2e/src/e2e/app.cy.ts"
        env:
          NODE_ENV: production
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
